[package]
name = "curios-ersd"
version.workspace = true
edition.workspace = true
description = "The curios erased IR: ersd->ersd optimization and lowering to continuations"

[dependencies]
curios-base = { workspace = true }
curios-cont = { workspace = true }
num-bigint = { workspace = true }
num-traits = { workspace = true }
