[package]
name = "curios-ersd"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "The Curios erased IR: post-erasure optimization and lowering to continuations"

[lints]
workspace = true

[features]
archive = ["dep:rkyv", "curios-abi/archive", "curios-base/archive"]
profile = ["curios-profile/enabled"]

[dependencies]
curios-profile = { workspace = true }
curios-abi = { workspace = true }
curios-base = { workspace = true }
curios-cont = { workspace = true }
num-bigint = { workspace = true }
rkyv = { workspace = true, optional = true }
