id = "curios"
name = "Curios"
version = "0.1.0"
schema_version = 1
authors = ["Valmir Pretto <valmirjunior0088@gmail.com>"]
description = "Curios language support for Zed"
repository = "https://github.com/valmirjunior0088/curios"

[grammars.curios]
repository = "https://github.com/valmirjunior0088/curios"
rev = "d90c63c461a3ffb7901f63fd02b3369daf5a1b1d"
path = "editors/grammar"
