use super::{
    BlockType, DataName, FieldName, FuncName, GlobalName, HeapType, LabelName, LocalName, RefType,
    TypeName, ValType,
};

/// The backend's instruction set, one variant per wasm opcode the crate can encode. Every operand the binary format expresses as an index — labels, functions, types, struct fields, locals, globals, data segments — is carried here as a name and resolved by the encoder, so emitters never track index spaces. The roster is deliberately GC-only for program values: struct/array/ref/`i31` operations plus the full numeric core, and the only route from raw bytes into values is `ArrayNewData` reading a passive data segment. The four memory instructions (`I32Load8U`/`I32Store8`/`MemorySize`/`MemoryGrow`) are not an exception to that rule — they serve the module's single always-emitted memory (empty until grown), a host-boundary bulk-copy lane that program values never inhabit.
#[derive(Debug, Clone)]
pub enum Instr {
    Unreachable,
    Nop,
    Block {
        label_name: LabelName,
        block_type: BlockType,
        instructions: Vec<Instr>,
    },
    Loop {
        label_name: LabelName,
        block_type: BlockType,
        instructions: Vec<Instr>,
    },
    If {
        label_name: LabelName,
        block_type: BlockType,
        then_instructions: Vec<Instr>,
        else_instructions: Vec<Instr>,
    },
    Br {
        label_name: LabelName,
    },
    BrIf {
        label_name: LabelName,
    },
    BrTable {
        label_names: Vec<LabelName>,
        label_name: LabelName,
    },
    Return,
    Call {
        func_name: FuncName,
    },
    CallRef {
        type_name: TypeName,
    },
    ReturnCall {
        func_name: FuncName,
    },
    ReturnCallRef {
        type_name: TypeName,
    },
    BrOnNull {
        label_name: LabelName,
    },
    BrOnNonNull {
        label_name: LabelName,
    },
    BrOnCast {
        label_name: LabelName,
        source_type: RefType,
        target_type: RefType,
    },
    BrOnCastFail {
        label_name: LabelName,
        source_type: RefType,
        target_type: RefType,
    },
    RefNull {
        heap_type: HeapType,
    },
    RefIsNull,
    RefFunc {
        func_name: FuncName,
    },
    RefEq,
    RefAsNonNull,
    StructNew {
        type_name: TypeName,
    },
    StructNewDefault {
        type_name: TypeName,
    },
    StructGet {
        type_name: TypeName,
        field_name: FieldName,
    },
    StructGetS {
        type_name: TypeName,
        field_name: FieldName,
    },
    StructGetU {
        type_name: TypeName,
        field_name: FieldName,
    },
    StructSet {
        type_name: TypeName,
        field_name: FieldName,
    },
    ArrayNew {
        type_name: TypeName,
    },
    ArrayNewDefault {
        type_name: TypeName,
    },
    ArrayNewFixed {
        type_name: TypeName,
        length: u32,
    },
    ArrayNewData {
        type_name: TypeName,
        data_name: DataName,
    },
    ArrayGet {
        type_name: TypeName,
    },
    ArrayGetS {
        type_name: TypeName,
    },
    ArrayGetU {
        type_name: TypeName,
    },
    ArraySet {
        type_name: TypeName,
    },
    ArrayLen,
    ArrayFill {
        type_name: TypeName,
    },
    ArrayCopy {
        source_name: TypeName,
        target_name: TypeName,
    },
    RefTest {
        ref_type: RefType,
    },
    RefCast {
        ref_type: RefType,
    },
    AnyConvertExtern,
    ExternConvertAny,
    RefI31,
    I31GetS,
    I31GetU,
    // The memory lane: byte-granular access (align 0, offset 0) plus size/grow against the module's single always-emitted memory.
    I32Load8U,
    I32Store8,
    MemorySize,
    MemoryGrow,
    Drop,
    Select {
        val_types: Vec<ValType>,
    },
    LocalGet {
        local_name: LocalName,
    },
    LocalSet {
        local_name: LocalName,
    },
    LocalTee {
        local_name: LocalName,
    },
    GlobalGet {
        global_name: GlobalName,
    },
    GlobalSet {
        global_name: GlobalName,
    },
    I32Const {
        value: i32,
    },
    I64Const {
        value: i64,
    },
    F32Const {
        value: f32,
    },
    F64Const {
        value: f64,
    },
    I32Eqz,
    I32Eq,
    I32Ne,
    I32LtS,
    I32LtU,
    I32GtS,
    I32GtU,
    I32LeS,
    I32LeU,
    I32GeS,
    I32GeU,
    I64Eqz,
    I64Eq,
    I64Ne,
    I64LtS,
    I64LtU,
    I64GtS,
    I64GtU,
    I64LeS,
    I64LeU,
    I64GeS,
    I64GeU,
    F32Eq,
    F32Ne,
    F32Lt,
    F32Gt,
    F32Le,
    F32Ge,
    F64Eq,
    F64Ne,
    F64Lt,
    F64Gt,
    F64Le,
    F64Ge,
    I32Clz,
    I32Ctz,
    I32Popcnt,
    I32Add,
    I32Sub,
    I32Mul,
    I32DivS,
    I32DivU,
    I32RemS,
    I32RemU,
    I32And,
    I32Or,
    I32Xor,
    I32Shl,
    I32ShrS,
    I32ShrU,
    I32Rotl,
    I32Rotr,
    I64Clz,
    I64Ctz,
    I64Popcnt,
    I64Add,
    I64Sub,
    I64Mul,
    I64DivS,
    I64DivU,
    I64RemS,
    I64RemU,
    I64And,
    I64Or,
    I64Xor,
    I64Shl,
    I64ShrS,
    I64ShrU,
    I64Rotl,
    I64Rotr,
    F32Abs,
    F32Neg,
    F32Ceil,
    F32Floor,
    F32Trunc,
    F32Nearest,
    F32Sqrt,
    F32Add,
    F32Sub,
    F32Mul,
    F32Div,
    F32Min,
    F32Max,
    F32Copysign,
    F64Abs,
    F64Neg,
    F64Ceil,
    F64Floor,
    F64Trunc,
    F64Nearest,
    F64Sqrt,
    F64Add,
    F64Sub,
    F64Mul,
    F64Div,
    F64Min,
    F64Max,
    F64Copysign,
    I32WrapI64,
    I32TruncF32S,
    I32TruncF32U,
    I32TruncF64S,
    I32TruncF64U,
    I64ExtendI32S,
    I64ExtendI32U,
    I64TruncF32S,
    I64TruncF32U,
    I64TruncF64S,
    I64TruncF64U,
    F32ConvertI32S,
    F32ConvertI32U,
    F32ConvertI64S,
    F32ConvertI64U,
    F32DemoteF64,
    F64ConvertI32S,
    F64ConvertI32U,
    F64ConvertI64S,
    F64ConvertI64U,
    F64PromoteF32,
    I32ReinterpretF32,
    I64ReinterpretF64,
    F32ReinterpretI32,
    F64ReinterpretI64,
    I32Extend8S,
    I32Extend16S,
    I64Extend8S,
    I64Extend16S,
    I64Extend32S,
    I32TruncSatF32S,
    I32TruncSatF32U,
    I32TruncSatF64S,
    I32TruncSatF64U,
    I64TruncSatF32S,
    I64TruncSatF32U,
    I64TruncSatF64S,
    I64TruncSatF64U,
}

/// Declares the operand-less instructions' WAT spellings from one table, so the printer's [`Instr::mnemonic`] and the parser's [`Instr::from_mnemonic`] cannot drift apart. The operand-carrying instructions stay hand-spelled in `print` and `parse`, where the compiler still forces an arm per variant.
macro_rules! mnemonics {
    ($($variant:ident => $mnemonic:literal,)+) => {
        impl Instr {
            /// The WAT spelling of an operand-less instruction; `None` for the operand-carrying forms the printer spells by hand.
            pub(crate) fn mnemonic(&self) -> Option<&'static str> {
                match self {
                    $(Instr::$variant => Some($mnemonic),)+
                    _ => None,
                }
            }

            /// The operand-less instruction spelled `token`, if any — [`Instr::mnemonic`]'s reverse, for the parser's whole-token dispatch.
            pub(crate) fn from_mnemonic(token: &str) -> Option<Instr> {
                match token {
                    $($mnemonic => Some(Instr::$variant),)+
                    _ => None,
                }
            }
        }
    };
}

mnemonics! {
    Unreachable => "unreachable",
    Nop => "nop",
    Return => "return",
    RefIsNull => "ref.is_null",
    RefEq => "ref.eq",
    RefAsNonNull => "ref.as_non_null",
    ArrayLen => "array.len",
    AnyConvertExtern => "any.convert_extern",
    ExternConvertAny => "extern.convert_any",
    RefI31 => "ref.i31",
    I31GetS => "i31.get_s",
    I31GetU => "i31.get_u",
    I32Load8U => "i32.load8_u",
    I32Store8 => "i32.store8",
    MemorySize => "memory.size",
    MemoryGrow => "memory.grow",
    Drop => "drop",
    I32Eqz => "i32.eqz",
    I32Eq => "i32.eq",
    I32Ne => "i32.ne",
    I32LtS => "i32.lt_s",
    I32LtU => "i32.lt_u",
    I32GtS => "i32.gt_s",
    I32GtU => "i32.gt_u",
    I32LeS => "i32.le_s",
    I32LeU => "i32.le_u",
    I32GeS => "i32.ge_s",
    I32GeU => "i32.ge_u",
    I64Eqz => "i64.eqz",
    I64Eq => "i64.eq",
    I64Ne => "i64.ne",
    I64LtS => "i64.lt_s",
    I64LtU => "i64.lt_u",
    I64GtS => "i64.gt_s",
    I64GtU => "i64.gt_u",
    I64LeS => "i64.le_s",
    I64LeU => "i64.le_u",
    I64GeS => "i64.ge_s",
    I64GeU => "i64.ge_u",
    F32Eq => "f32.eq",
    F32Ne => "f32.ne",
    F32Lt => "f32.lt",
    F32Gt => "f32.gt",
    F32Le => "f32.le",
    F32Ge => "f32.ge",
    F64Eq => "f64.eq",
    F64Ne => "f64.ne",
    F64Lt => "f64.lt",
    F64Gt => "f64.gt",
    F64Le => "f64.le",
    F64Ge => "f64.ge",
    I32Clz => "i32.clz",
    I32Ctz => "i32.ctz",
    I32Popcnt => "i32.popcnt",
    I32Add => "i32.add",
    I32Sub => "i32.sub",
    I32Mul => "i32.mul",
    I32DivS => "i32.div_s",
    I32DivU => "i32.div_u",
    I32RemS => "i32.rem_s",
    I32RemU => "i32.rem_u",
    I32And => "i32.and",
    I32Or => "i32.or",
    I32Xor => "i32.xor",
    I32Shl => "i32.shl",
    I32ShrS => "i32.shr_s",
    I32ShrU => "i32.shr_u",
    I32Rotl => "i32.rotl",
    I32Rotr => "i32.rotr",
    I64Clz => "i64.clz",
    I64Ctz => "i64.ctz",
    I64Popcnt => "i64.popcnt",
    I64Add => "i64.add",
    I64Sub => "i64.sub",
    I64Mul => "i64.mul",
    I64DivS => "i64.div_s",
    I64DivU => "i64.div_u",
    I64RemS => "i64.rem_s",
    I64RemU => "i64.rem_u",
    I64And => "i64.and",
    I64Or => "i64.or",
    I64Xor => "i64.xor",
    I64Shl => "i64.shl",
    I64ShrS => "i64.shr_s",
    I64ShrU => "i64.shr_u",
    I64Rotl => "i64.rotl",
    I64Rotr => "i64.rotr",
    F32Abs => "f32.abs",
    F32Neg => "f32.neg",
    F32Ceil => "f32.ceil",
    F32Floor => "f32.floor",
    F32Trunc => "f32.trunc",
    F32Nearest => "f32.nearest",
    F32Sqrt => "f32.sqrt",
    F32Add => "f32.add",
    F32Sub => "f32.sub",
    F32Mul => "f32.mul",
    F32Div => "f32.div",
    F32Min => "f32.min",
    F32Max => "f32.max",
    F32Copysign => "f32.copysign",
    F64Abs => "f64.abs",
    F64Neg => "f64.neg",
    F64Ceil => "f64.ceil",
    F64Floor => "f64.floor",
    F64Trunc => "f64.trunc",
    F64Nearest => "f64.nearest",
    F64Sqrt => "f64.sqrt",
    F64Add => "f64.add",
    F64Sub => "f64.sub",
    F64Mul => "f64.mul",
    F64Div => "f64.div",
    F64Min => "f64.min",
    F64Max => "f64.max",
    F64Copysign => "f64.copysign",
    I32WrapI64 => "i32.wrap_i64",
    I32TruncF32S => "i32.trunc_f32_s",
    I32TruncF32U => "i32.trunc_f32_u",
    I32TruncF64S => "i32.trunc_f64_s",
    I32TruncF64U => "i32.trunc_f64_u",
    I64ExtendI32S => "i64.extend_i32_s",
    I64ExtendI32U => "i64.extend_i32_u",
    I64TruncF32S => "i64.trunc_f32_s",
    I64TruncF32U => "i64.trunc_f32_u",
    I64TruncF64S => "i64.trunc_f64_s",
    I64TruncF64U => "i64.trunc_f64_u",
    F32ConvertI32S => "f32.convert_i32_s",
    F32ConvertI32U => "f32.convert_i32_u",
    F32ConvertI64S => "f32.convert_i64_s",
    F32ConvertI64U => "f32.convert_i64_u",
    F32DemoteF64 => "f32.demote_f64",
    F64ConvertI32S => "f64.convert_i32_s",
    F64ConvertI32U => "f64.convert_i32_u",
    F64ConvertI64S => "f64.convert_i64_s",
    F64ConvertI64U => "f64.convert_i64_u",
    F64PromoteF32 => "f64.promote_f32",
    I32ReinterpretF32 => "i32.reinterpret_f32",
    I64ReinterpretF64 => "i64.reinterpret_f64",
    F32ReinterpretI32 => "f32.reinterpret_i32",
    F64ReinterpretI64 => "f64.reinterpret_i64",
    I32Extend8S => "i32.extend8_s",
    I32Extend16S => "i32.extend16_s",
    I64Extend8S => "i64.extend8_s",
    I64Extend16S => "i64.extend16_s",
    I64Extend32S => "i64.extend32_s",
    I32TruncSatF32S => "i32.trunc_sat_f32_s",
    I32TruncSatF32U => "i32.trunc_sat_f32_u",
    I32TruncSatF64S => "i32.trunc_sat_f64_s",
    I32TruncSatF64U => "i32.trunc_sat_f64_u",
    I64TruncSatF32S => "i64.trunc_sat_f32_s",
    I64TruncSatF32U => "i64.trunc_sat_f32_u",
    I64TruncSatF64S => "i64.trunc_sat_f64_s",
    I64TruncSatF64U => "i64.trunc_sat_f64_u",
}

/// A flat instruction sequence — a function body or a global's constant initializer. The encoder appends the terminating `end` opcode itself, so builders supply only the instructions.
#[derive(Debug, Default, Clone)]
pub struct Expr {
    pub instrs: Vec<Instr>,
}

impl Expr {
    /// Appends a single instruction.
    pub fn push(&mut self, instr: Instr) {
        self.instrs.push(instr)
    }

    /// Appends a sequence of instructions in order.
    pub fn extend<I>(&mut self, instrs: I)
    where
        I: IntoIterator<Item = Instr>,
    {
        self.instrs.extend(instrs);
    }
}

impl<I> From<I> for Expr
where
    I: IntoIterator<Item = Instr>,
{
    fn from(value: I) -> Self {
        Self {
            instrs: value.into_iter().collect(),
        }
    }
}
