[workspace]
resolver = "2"
members = ["curios-abi", "curios-base", "curios-wasm", "curios-cont", "curios-ersd", "curios-core", "curios", "curios-binaryen", "curios-runtime", "curios-compiler"]

[workspace.package]
version = "0.1.0"
edition = "2024"
description = "Work-in-progress functional dependently typed programming language"

[workspace.dependencies]
curios = { path = "curios" }
curios-abi = { path = "curios-abi" }
curios-base = { path = "curios-base" }
curios-wasm = { path = "curios-wasm" }
curios-cont = { path = "curios-cont" }
curios-ersd = { path = "curios-ersd" }
curios-core = { path = "curios-core" }
curios-binaryen = { path = "curios-binaryen" }
curios-runtime = { path = "curios-runtime" }
curios-compiler = { path = "curios-compiler" }
wasmtime = { version = "44.0.1", default-features = false, features = ["runtime", "gc", "gc-drc", "std"] }
num-bigint = { version = "0.4.6" }
num-traits = { version = "0.2.19" }
