name: curios
version: 0.1.0.0
github: "valmirjunior0088/curios"
license: BSD3
author: "Valmir Junior"
maintainer: "valmirjunior0088@gmail.com"
copyright: "2019 Valmir Junior"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis: Curios
category: Compiler
description: Please see the README on GitHub at <https://github.com/valmirjunior0088/curios#readme>

dependencies:
- base >= 4 && < 5
- megaparsec >= 7 && < 8
- boxes >= 0 && < 1
- containers >= 0 && < 1

library:
  source-dirs: src

executables:
  curios-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - curios

tests:
  curios-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - curios
    - hspec >= 2 && < 3
    - hspec-megaparsec >= 2 && < 3
