name: curios
version: 0.1.0
github: "valmirjunior0088/curios"
license: BSD3
author: "Valmir Pretto"
maintainer: "valmirjunior0088@gmail.com"
copyright: "2019-present Valmir Pretto"

extra-source-files:
- README.md

synopsis: Curios
category: Compiler
description: Please see the README on GitHub at <https://github.com/valmirjunior0088/curios#readme>

dependencies:
- base >= 4.7 && < 5
- mtl >= 2.2 && < 3
- bytestring >= 0.10 && < 1
- megaparsec >= 9.2 && < 10
- containers >= 0.6 && < 1

# Lens specific dependencies
- lens >= 5.0 && < 6
- generic-lens >= 2.2 && < 3

default-extensions:
- BinaryLiterals
- LambdaCase
- ParallelListComp
- NamedFieldPuns
- NoFieldSelectors
- DuplicateRecordFields
- FlexibleContexts
- GeneralizedNewtypeDeriving

# Lens specific extensions
- DeriveGeneric
- DataKinds
- TypeApplications

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  curios-compiler:
    main: Main.hs
    source-dirs: compiler
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - curios

  curios-interpreter:
    main: Main.hs
    source-dirs: interpreter
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - curios

  curios-server:
    main: Main.hs
    source-dirs: server
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - warp >= 3.3 && < 4
    - wai >= 3.2 && < 4
    - wai-app-static >= 3.1 && < 4