name: curios
version: 0.0.3
github: "valmirjunior0088/curios"
license: BSD3
author: "Valmir Pretto"
maintainer: "valmirjunior0088@gmail.com"
copyright: "2019-present Valmir Pretto"

extra-source-files:
- README.md

synopsis: Curios
category: Compiler
description: Please see the README on GitHub at <https://github.com/valmirjunior0088/curios#readme>

dependencies:
- base >= 4.7 && < 5
- mtl >= 2.2 && < 3
- megaparsec >= 9.0 && < 10
- boxes >= 0.1 && < 1
- containers >= 0.6 && < 7

library:
  source-dirs: src

executables:
  curios-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - curios

tests:
  curios-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - curios
