//! One-time validation and per-thread restoration of the generated image: a [`Unit`], archived by the build script exactly as a store slot archives one.

use {
    curios_unit::{ArchivedUnit, Unit},
    std::{cell::LazyCell, sync::OnceLock},
};

// From `.artifacts/` beside this crate, where the build script files it, rather than from `OUT_DIR`: the image is also read by `curios document` to render the standard library's pages, and one image in one nameable place is what keeps the pages and the compiler agreeing about what the library is.
const BYTES: &[u8] = include_bytes!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/.artifacts/archive.rkyv"
));

static ARCHIVE: OnceLock<Result<&'static ArchivedUnit, String>> = OnceLock::new();

thread_local! {
    /// The reusable, restored fixed prelude, as the unit it is. Held behind [`with_prelude`] so callers cannot mutate compiler-global state between invocations.
    static PRELUDE: LazyCell<Unit> = LazyCell::new(restore_archive);
}

fn validate_archive() -> Result<&'static ArchivedUnit, String> {
    curios_profile::profile!("validate_archive");
    validate_bytes(BYTES)
}

/// Validate through the zero-copy view — bytecheck for structural validity — without deserializing the image, whose full restoration is per-thread and on demand.
///
/// There is deliberately no content-digest check. The archive reaches this function through `include_bytes!`, so it is a constant in the executable's own read-only data, and a digest computed by `build.rs` would be another constant from the same build: hashing one to compare it against the other could not fail except under corruption of our own image, and would cover only the prelude rather than any of the compiler's code. It could not detect a stale or substituted archive, because there is no runtime file to be stale or substituted. Bytecheck is what does real work here — it is what makes handing out references into these bytes sound. Nor is there an image from another build to reject: the bytes are regenerated by the build that compiles this line, so the schema and source fingerprint that once rode beside them could only ever compare a build against itself.
fn validate_bytes(bytes: &[u8]) -> Result<&ArchivedUnit, String> {
    curios_archive::access::<ArchivedUnit>(bytes)
        .map_err(|error| format!("invalid archived prelude: {error}"))
}

fn archived() -> &'static ArchivedUnit {
    match ARCHIVE.get_or_init(validate_archive) {
        Ok(archived) => archived,
        Err(error) => panic!("{error}"),
    }
}

/// Deserialize the validated image.
///
/// The universe invariants are *not* re-checked here. They are asserted once by `build.rs`, on the value it is about to serialize, and these bytes are exactly the bytes written from that value — a constant of the same build, whose structure [`validate_bytes`] confirms. Walking the whole standard library again per compilation to re-derive an answer already settled cost ~175 ms of a ~680 ms release compile of a one-line program.
fn restore_archive() -> Unit {
    curios_profile::profile!("restore_archive");
    curios_archive::deserialize::<Unit>(archived())
        .unwrap_or_else(|error| panic!("validated archived prelude failed to restore: {error}"))
}

/// Borrow this thread's reusable restored prelude unit.
pub fn with_prelude<R>(use_prelude: impl FnOnce(&Unit) -> R) -> R {
    curios_profile::profile!("with_prelude");
    PRELUDE.with(|prelude| use_prelude(prelude))
}

#[cfg(test)]
mod tests;
