//! One-time validation and per-thread restoration of the generated images: two [`Unit`]s, `/sys` then `/std`, each archived by the build script exactly as a store slot archives one.

use {
    curios_unit::{ArchivedUnit, Unit},
    std::{cell::LazyCell, sync::OnceLock},
};

// From `.artifacts/` beside this crate, where the build script files them, rather than from `OUT_DIR`: `std.rkyv` is also read by `curios document` to render the standard library's pages, and one image in one nameable place is what keeps the pages and the compiler agreeing about what the library is.
//
// Two images rather than one paired file, because each is a unit and a unit is what a store slot holds: a pair would be a third framing beside the two `curios-verdicts` defines, and the fold that consumes these wants them separately anyway.
const SYS_BYTES: &[u8] =
    include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/.artifacts/sys.rkyv"));
const STD_BYTES: &[u8] =
    include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/.artifacts/std.rkyv"));

/// The prelude's roots in dependency order, as the build script folded them: `/sys` is lowered against nothing and `/std` against `/sys`, so restoring them in any other order would hand a successor a scope its own names were never resolved in.
const ROOTS: [(&str, &[u8]); 2] = [("sys", SYS_BYTES), ("std", STD_BYTES)];

static ARCHIVES: OnceLock<[Result<&'static ArchivedUnit, String>; 2]> = OnceLock::new();

thread_local! {
    /// The reusable, restored fixed prelude, as the units it is, in dependency order. Held behind [`with_prelude`] so callers cannot mutate compiler-global state between invocations.
    static PRELUDE: LazyCell<[Unit; 2]> = LazyCell::new(restore_archives);
}

fn validate_archives() -> [Result<&'static ArchivedUnit, String>; 2] {
    curios_profile::profile!("validate_archives");
    ROOTS.map(|(root, bytes)| validate_bytes(root, bytes))
}

/// Validate through the zero-copy view — bytecheck for structural validity — without deserializing the image, whose full restoration is per-thread and on demand.
///
/// There is deliberately no content-digest check. The archive reaches this function through `include_bytes!`, so it is a constant in the executable's own read-only data, and a digest computed by `build.rs` would be another constant from the same build: hashing one to compare it against the other could not fail except under corruption of our own image, and would cover only the prelude rather than any of the compiler's code. It could not detect a stale or substituted archive, because there is no runtime file to be stale or substituted. Bytecheck is what does real work here — it is what makes handing out references into these bytes sound. Nor is there an image from another build to reject: the bytes are regenerated by the build that compiles this line, so the schema and source fingerprint that once rode beside them could only ever compare a build against itself.
fn validate_bytes(root: &str, bytes: &'static [u8]) -> Result<&'static ArchivedUnit, String> {
    curios_archive::access::<ArchivedUnit>(bytes)
        .map_err(|error| format!("invalid archived /{root}: {error}"))
}

fn archived() -> &'static [Result<&'static ArchivedUnit, String>; 2] {
    ARCHIVES.get_or_init(validate_archives)
}

/// Deserialize the validated images.
///
/// The universe invariants are *not* re-checked here. They are asserted once by `build.rs`, on the values it is about to serialize, and these bytes are exactly the bytes written from those values — constants of the same build, whose structure [`validate_bytes`] confirms. Walking the whole standard library again per compilation to re-derive an answer already settled cost ~175 ms of a ~680 ms release compile of a one-line program.
fn restore_archives() -> [Unit; 2] {
    curios_profile::profile!("restore_archives");
    let mut units = archived().iter().zip(ROOTS).map(|(archived, (root, _))| {
        let archived = match archived {
            Ok(archived) => *archived,
            Err(error) => panic!("{error}"),
        };

        curios_archive::deserialize::<Unit>(archived)
            .unwrap_or_else(|error| panic!("validated archived /{root} failed to restore: {error}"))
    });

    [
        units.next().expect("the prelude has two roots"),
        units.next().expect("the prelude has two roots"),
    ]
}

/// Borrow this thread's reusable restored prelude, as the ordered prefix every compilation starts from.
///
/// A slice rather than one unit, and in dependency order rather than any: what `Prefix::over` takes is exactly this, so a product puts the whole prelude in scope by handing it along instead of deciding how its roots compose.
pub fn with_prelude<R>(use_prelude: impl FnOnce(&[&Unit]) -> R) -> R {
    curios_profile::profile!("with_prelude");
    PRELUDE.with(|prelude| {
        let [sys, std] = &**prelude;
        use_prelude(&[sys, std])
    })
}

#[cfg(test)]
mod tests;
