//! One-time validation and per-thread restoration of the generated images: two stored units, `/sys` then `/std`, each archived by the build script exactly as a store slot archives one — a record of what the root was compiled from, framed ahead of the [`Unit`].

use {
    curios_unit::{ArchivedRecord, ArchivedUnit, Record, Stored, Unit, segments},
    std::{cell::LazyCell, sync::OnceLock},
};

// From `.artifacts/` beside this crate, where the build script files them, rather than from `OUT_DIR`: `std.rkyv` is also read by `curios document` to render the standard library's pages, and one image in one nameable place is what keeps the pages and the compiler agreeing about what the library is.
//
// Two images rather than one paired file, because each is a stored unit and a stored unit is what a store slot holds: a pair would be a second framing beside the one `curios-unit` defines, and the fold that consumes these wants them separately anyway.
const SYS_BYTES: &[u8] =
    include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/.artifacts/sys.rkyv"));
const STD_BYTES: &[u8] =
    include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/.artifacts/std.rkyv"));

/// The prelude's roots in dependency order, as the build script folded them: `/sys` is lowered against nothing and `/std` against `/sys`, so restoring them in any other order would hand a successor a scope its own names were never resolved in.
const ROOTS: [(&str, &[u8]); 2] = [("sys", SYS_BYTES), ("std", STD_BYTES)];

/// One image validated: its record and its unit, each as the zero-copy view bytecheck confirmed.
type Validated = Result<(&'static ArchivedRecord, &'static ArchivedUnit), String>;

static ARCHIVES: OnceLock<[Validated; 2]> = OnceLock::new();

thread_local! {
    /// The reusable, restored fixed prelude: each root's record beside its unit, in dependency order. Held behind [`with_prelude`] and [`with_stored`] so callers cannot mutate compiler-global state between invocations.
    static PRELUDE: LazyCell<[Stored; 2]> = LazyCell::new(restore_archives);
}

fn validate_archives() -> [Validated; 2] {
    curios_profile::profile!("validate_archives");
    ROOTS.map(|(root, bytes)| validate_bytes(root, bytes))
}

/// Validate through the zero-copy view — bytecheck for structural validity — without deserializing the image, whose full restoration is per-thread and on demand. The image is a stored unit, so it is split at the one framing `curios-unit` states before either half is checked.
///
/// There is deliberately no content-digest check. The archive reaches this function through `include_bytes!`, so it is a constant in the executable's own read-only data, and a digest computed by `build.rs` would be another constant from the same build: hashing one to compare it against the other could not fail except under corruption of our own image, and would cover only the prelude rather than any of the compiler's code. It could not detect a stale or substituted archive, because there is no runtime file to be stale or substituted. Bytecheck is what does real work here — it is what makes handing out references into these bytes sound. Nor is there an image from another build to reject: the bytes are regenerated by the build that compiles this line, so the schema and source fingerprint that once rode beside them could only ever compare a build against itself.
///
/// The record is not checked against anything here either, for the same reason: nothing in this process is about to believe a verdict on its strength. It is carried for the one consumer that asks which tree an image was built from — the fold, deciding whether a unit claiming a prelude prefix is that tree — and that consumer reads what it needs at the seam it needs it.
fn validate_bytes(root: &str, bytes: &'static [u8]) -> Validated {
    let (record, unit) =
        segments(bytes).ok_or_else(|| format!("invalid archived /{root}: not a stored unit"))?;
    let record = curios_archive::access::<ArchivedRecord>(record)
        .map_err(|error| format!("invalid archived /{root} record: {error}"))?;
    let unit = curios_archive::access::<ArchivedUnit>(unit)
        .map_err(|error| format!("invalid archived /{root}: {error}"))?;

    Ok((record, unit))
}

fn archived() -> &'static [Validated; 2] {
    ARCHIVES.get_or_init(validate_archives)
}

/// Deserialize the validated images.
///
/// The universe invariants are *not* re-checked here. They are asserted once by `build.rs`, on the values it is about to serialize, and these bytes are exactly the bytes written from those values — constants of the same build, whose structure [`validate_bytes`] confirms. Walking the whole standard library again per compilation to re-derive an answer already settled cost ~175 ms of a ~680 ms release compile of a one-line program.
fn restore_archives() -> [Stored; 2] {
    curios_profile::profile!("restore_archives");
    let mut units = archived().iter().zip(ROOTS).map(|(archived, (root, _))| {
        let (record, unit) = match archived {
            Ok(archived) => *archived,
            Err(error) => panic!("{error}"),
        };

        Stored {
            record: curios_archive::deserialize::<Record>(record).unwrap_or_else(|error| {
                panic!("validated archived /{root} record failed to restore: {error}")
            }),
            unit: curios_archive::deserialize::<Unit>(unit).unwrap_or_else(|error| {
                panic!("validated archived /{root} failed to restore: {error}")
            }),
        }
    });

    [
        units.next().expect("the prelude has two roots"),
        units.next().expect("the prelude has two roots"),
    ]
}

/// Borrow this thread's reusable restored prelude, as the ordered prefix every compilation starts from.
///
/// A slice rather than one unit, and in dependency order rather than any: what `Prefix::over` takes is exactly this, so a product puts the whole prelude in scope by handing it along instead of deciding how its roots compose.
pub fn with_prelude<R>(use_prelude: impl FnOnce(&[&Unit]) -> R) -> R {
    curios_profile::profile!("with_prelude");
    PRELUDE.with(|prelude| {
        let [sys, std] = &**prelude;
        use_prelude(&[&sys.unit, &std.unit])
    })
}

/// Borrow this thread's restored prelude with each root's record beside its unit, in the same order — for the one consumer that asks which tree an image was built from. Everything that wants the prefix alone wants [`with_prelude`].
pub fn with_stored<R>(use_stored: impl FnOnce(&[&Stored]) -> R) -> R {
    curios_profile::profile!("with_stored");
    PRELUDE.with(|prelude| {
        let [sys, std] = &**prelude;
        use_stored(&[sys, std])
    })
}

#[cfg(test)]
mod tests;
