use std::path::Path;

// `src/runtime` is the slim launcher embedded via `include_bytes!`; it is
// generated by the Makefile. Fail with a clear pointer when it is missing.
fn main() {
    println!("cargo:rerun-if-changed=src/runtime");

    if !Path::new("src/runtime").exists() {
        panic!("missing embedded launcher (src/runtime); use `make` to build it");
    }
}
