[package]
name = "curios-core"
version.workspace = true
edition.workspace = true
description = "The curios core language: elaboration, typing, reduction, conversion, and erasure"

[dependencies]
curios-base = { workspace = true }
curios-ersd = { workspace = true }
num-bigint = { workspace = true }
num-traits = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-time = { workspace = true }
