use {
    super::{Nat, Term},
    curios_num::{Flt, Integer},
    curios_utilities::Grain,
};

/// One entry of a list literal `[a, ..xs, b]` — a plain element, or a `..`-spread whose term contributes a whole `List` run. Lowering groups consecutive elements into literal chunks and splices the spreads with the n-ary `ListConcat` intrinsic; a spread-free literal lowers to a plain `List` exactly as before.
#[derive(Debug, Clone, PartialEq)]
pub enum ListEntry {
    Elem(Term),
    Spread(Term),
}

/// One entry of a `Bytes` literal `x[\00, byte, ..bytes, \01]` — a run of escaped literal bytes, a term contributing one atom, or a `..`-spread whose term contributes a whole `Bytes` run. Entries are comma-delimited, so an atom or spread operand is an arbitrary term.
#[derive(Debug, Clone, PartialEq)]
pub enum BinSegment {
    /// A single atom given by a term: a `Bool` under `Grain::B`, a `Byte` under `Grain::X`. The free monoid's generator, where [`BinSegment::Spread`] carries a whole element. A constant atom is an ordinary numeral term — `Byte` and `Bool` both realize numerals — and lowering folds adjacent constant atoms into one packed run, so the AST needs no constant-run variant of its own.
    Atom(Term),
    Spread(Term),
}

/// The hardcoded intrinsic vocabulary, shaped after `curios_elab::Intrinsic` rather than after the written syntax (`Nat`'s payload still differs, keeping surface-only detail like radix and spread segments — `Int`/`Flt` share `Int`/`Flt` verbatim, since neither carries any surface-only presentation state): the scalar carriers (`Bool`/`Nat`/`Int`/`Flt`) with their type formers, literal values, and operators, the conversions between them, the packed `Bits`/`Bytes` and `List` free-monoid carriers with their literals and accessors, `Handle` with the store-described `Foreign` host calls, and the `Cell` mutable reference. The parser only ever produces the literal-value variants (`Bool`/`Nat`/`Flt`/packed binary/`List`); every other variant — type formers and operations alike — is baked directly into the embedded `sys` prelude's definition bodies (see `prelude`), so user code reaches them as ordinary named bindings rather than syntax.
#[derive(Debug, Clone, PartialEq)]
pub enum Intrinsic {
    BoolType,
    Bool(bool),
    BoolAnd(Term, Term),
    BoolOr(Term, Term),
    BoolXor(Term, Term),
    BoolEql(Term, Term),
    BoolNeq(Term, Term),
    NatType,
    Nat(Nat),
    NatEql(Term, Term),
    NatNeq(Term, Term),
    NatAdd(Term, Term),
    NatSub(Term, Term),
    NatMul(Term, Term),
    NatLt(Term, Term),
    /// `non_zero` is the proof the `/sys` declaration takes as its implicit third argument, carried into the node so the bound survives lowering rather than staying an unused parameter.
    NatDiv {
        dividend: Term,
        divisor: Term,
        non_zero: Term,
    },
    NatRem {
        dividend: Term,
        divisor: Term,
        non_zero: Term,
    },
    NatGt(Term, Term),
    NatLte(Term, Term),
    NatGte(Term, Term),
    NatAnd(Term, Term),
    NatOr(Term, Term),
    NatXor(Term, Term),
    NatShl(Term, Term),
    NatShr(Term, Term),
    NatRotl(Term, Term),
    NatRotr(Term, Term),
    NatClz(Term),
    NatCtz(Term),
    NatPopcnt(Term),
    ByteType,
    Byte(u8),
    ByteToNat(Term),
    NatToByte(Term),
    ByteEql(Term, Term),
    ByteLt(Term, Term),
    ByteLte(Term, Term),
    ByteGt(Term, Term),
    ByteGte(Term, Term),
    IntType,
    Int(Integer),
    IntEql(Term, Term),
    IntNeq(Term, Term),
    IntAdd(Term, Term),
    IntSub(Term, Term),
    IntMul(Term, Term),
    IntDiv {
        dividend: Term,
        divisor: Term,
        non_zero: Term,
    },
    IntRem {
        dividend: Term,
        divisor: Term,
        non_zero: Term,
    },
    IntLt(Term, Term),
    IntGt(Term, Term),
    IntLte(Term, Term),
    IntGte(Term, Term),
    IntAnd(Term, Term),
    IntOr(Term, Term),
    IntXor(Term, Term),
    IntShl(Term, Term),
    IntShr(Term, Term),
    IntRotl(Term, Term),
    IntRotr(Term, Term),
    IntClz(Term),
    IntCtz(Term),
    IntPopcnt(Term),
    FltType,
    Flt(Flt),
    FltAdd(Term, Term),
    FltSub(Term, Term),
    FltMul(Term, Term),
    FltDiv(Term, Term),
    FltRem(Term, Term),
    FltEql(Term, Term),
    FltNeq(Term, Term),
    FltLt(Term, Term),
    FltGt(Term, Term),
    FltLte(Term, Term),
    FltGte(Term, Term),
    FltMin(Term, Term),
    FltMax(Term, Term),
    FltNeg(Term),
    FltAbs(Term),
    FltSqrt(Term),
    FltFloor(Term),
    FltCeil(Term),
    FltTrunc(Term),
    FltNearest(Term),
    FltCopysign(Term, Term),
    NatToInt(Term),
    NatToFlt(Term),
    IntToNat(Term),
    IntToFlt(Term),
    FltToNat(Term),
    FltToLeBytes(Term),
    FltOfLeBytes {
        bin: Term,
        four_bytes: Term,
    },
    FltToInt(Term),
    BinType(Grain),
    Bin(Grain, Vec<BinSegment>),
    BinLen(Grain, Term),
    BinEql(Grain, Term, Term),
    BinGet {
        grain: Grain,
        bin: Term,
        index: Term,
    },
    BinSlice {
        grain: Grain,
        bin: Term,
        start: Term,
        end: Term,
    },
    BinAppend {
        grain: Grain,
        bin: Term,
        element: Term,
    },
    BinConcat {
        grain: Grain,
        left: Term,
        right: Term,
    },
    ListType(Term),
    List(Vec<ListEntry>),
    ListLen {
        element: Term,
        list: Term,
    },
    ListGet {
        element: Term,
        list: Term,
        index: Term,
    },
    ListSlice {
        element: Term,
        list: Term,
        start: Term,
        end: Term,
    },
    ListAppend {
        element: Term,
        list: Term,
        item: Term,
    },
    ListConcat {
        element: Term,
        left: Term,
        right: Term,
    },
    ListMap {
        from: Term,
        to: Term,
        list: Term,
        function: Term,
    },
    HandleType,
    Handle(u32),
    HandleEql(Term, Term),
    ProcExit(Term),
    CellType(Term),
    Cell {
        element: Term,
        initial: Term,
    },
    CellSet {
        element: Term,
        cell: Term,
        value: Term,
    },
    CellGet {
        element: Term,
        cell: Term,
    },
    IoType(Term),
    IoPure {
        result: Term,
        value: Term,
    },
    IoBind {
        from: Term,
        to: Term,
        action: Term,
        continuation: Term,
    },
}
