use {
    super::{Nat, Term},
    curios_abi::ForeignFunction,
    curios_base::{Flt, Grain, Int},
    std::sync::Arc,
};

/// One entry of a list literal `[a, ..xs, b]` — a plain element, or a `..`-spread whose term contributes a whole `Lst` run. Lowering groups consecutive elements into literal chunks and splices the spreads with the n-ary `LstConcat` primitive; a spread-free literal lowers to a plain `Lst` exactly as before.
#[derive(Debug, Clone, PartialEq)]
pub enum LstEntry {
    Elem(Term),
    Spread(Term),
}

/// One entry of a `Bytes` literal `x[\00, byte, ..bytes, \01]` — a run of escaped literal bytes, a term contributing one atom, or a `..`-spread whose term contributes a whole `Bytes` run. Entries are comma-delimited, so an atom or spread operand is an arbitrary term.
#[derive(Debug, Clone, PartialEq)]
pub enum BinSegment {
    /// A run of literal bytes, written `\XX` (or `\0`/`\1` under `Grain::B`). Invariant (maintained by the parser): never empty, and never adjacent to another `Bytes` run.
    Bytes(Vec<u8>),
    /// A single atom given by a term: a `Bool` under `Grain::B`, a `Byte` under `Grain::X`. The free monoid's generator, where [`BinSegment::Spread`] carries a whole element — a literal run is this same generator at values the parser already knows, which is why lowering folds a constant term back into the neighbouring run.
    Atom(Term),
    Spread(Term),
}

/// The hardcoded primitive vocabulary, shaped after `curios_elab::Prim` rather than after the written syntax (`Nat`'s payload still differs, keeping surface-only detail like radix and spread segments — `Int`/`Flt` share `Int`/`Flt` verbatim, since neither carries any surface-only presentation state): the scalar carriers (`Bool`/`Nat`/`Int`/`Flt`) with their type formers, literal values, and operators, the conversions between them, the packed `Bits`/`Bytes` and `Lst` free-monoid carriers with their literals and accessors, `Handle` with the store-described `Foreign` host calls, and the `Cell` mutable reference. The parser only ever produces the literal-value variants (`Bool`/`Nat`/`Flt`/packed binary/`Lst`); every other variant — type formers and operations alike — is baked directly into the embedded `sys` prelude's definition bodies (see `prelude`), so user code reaches them as ordinary named bindings rather than syntax.
#[derive(Debug, Clone, PartialEq)]
pub enum Prim {
    BoolType,
    Bool(bool),
    BoolAnd(Term, Term),
    BoolOr(Term, Term),
    BoolXor(Term, Term),
    BoolEql(Term, Term),
    BoolNeq(Term, Term),
    NatType,
    Nat(Nat),
    NatEql(Term, Term),
    NatNeq(Term, Term),
    NatAdd(Term, Term),
    NatSub(Term, Term),
    NatMul(Term, Term),
    NatLt(Term, Term),
    NatDiv(Term, Term),
    NatRem(Term, Term),
    NatGt(Term, Term),
    NatLte(Term, Term),
    NatGte(Term, Term),
    NatAnd(Term, Term),
    NatOr(Term, Term),
    NatXor(Term, Term),
    NatShl(Term, Term),
    NatShr(Term, Term),
    NatRotl(Term, Term),
    NatRotr(Term, Term),
    NatClz(Term),
    NatCtz(Term),
    NatPopcnt(Term),
    ByteType,
    Byte(u8),
    ByteToNat(Term),
    NatToByte(Term),
    ByteEql(Term, Term),
    ByteLt(Term, Term),
    ByteLte(Term, Term),
    ByteGt(Term, Term),
    ByteGte(Term, Term),
    IntType,
    Int(Int),
    IntEql(Term, Term),
    IntNeq(Term, Term),
    IntAdd(Term, Term),
    IntSub(Term, Term),
    IntMul(Term, Term),
    IntDiv(Term, Term),
    IntRem(Term, Term),
    IntLt(Term, Term),
    IntGt(Term, Term),
    IntLte(Term, Term),
    IntGte(Term, Term),
    IntAnd(Term, Term),
    IntOr(Term, Term),
    IntXor(Term, Term),
    IntShl(Term, Term),
    IntShr(Term, Term),
    IntRotl(Term, Term),
    IntRotr(Term, Term),
    IntClz(Term),
    IntCtz(Term),
    IntPopcnt(Term),
    FltType,
    Flt(Flt),
    FltAdd(Term, Term),
    FltSub(Term, Term),
    FltMul(Term, Term),
    FltDiv(Term, Term),
    FltRem(Term, Term),
    FltEql(Term, Term),
    FltNeq(Term, Term),
    FltLt(Term, Term),
    FltGt(Term, Term),
    FltLte(Term, Term),
    FltGte(Term, Term),
    FltMin(Term, Term),
    FltMax(Term, Term),
    FltNeg(Term),
    FltAbs(Term),
    FltSqrt(Term),
    FltFloor(Term),
    FltCeil(Term),
    FltTrunc(Term),
    FltNearest(Term),
    FltCopysign(Term, Term),
    NatToInt(Term),
    NatToFlt(Term),
    IntToNat(Term),
    IntToFlt(Term),
    FltToNat(Term),
    FltToLeBytes(Term),
    FltOfLeBytes(Term),
    FltToInt(Term),
    BinType(Grain),
    Bin(Grain, Vec<BinSegment>),
    BinLen(Grain, Term),
    BinEql(Grain, Term, Term),
    BinGet(Grain, Term, Term),
    BinSlice(Grain, Term, Term, Term),
    BinAppend(Grain, Term, Term),
    BinConcat(Grain, Term, Term),
    LstType(Term),
    Lst(Vec<LstEntry>),
    LstLen(Term, Term),
    LstGet(Term, Term, Term),
    LstSlice(Term, Term, Term, Term),
    LstAppend(Term, Term, Term),
    LstConcat(Term, Term, Term),
    LstMap(Term, Term, Term, Term),
    HandleType,
    Handle(u32),
    HandleEql(Term, Term),
    // A store-described host call; the prelude bakes it into the `/sys/Handle` declaration whose parameters the argument terms name.
    Foreign(Arc<ForeignFunction>, Vec<Term>),
    Exit(Term),
    CellType(Term),
    Cell(Term, Term),          // type, init
    CellSet(Term, Term, Term), // type, cell, value
    CellGet(Term, Term),       // type, cell
    IoType(Term),
    IoPure(Term, Term),             // type, value
    IoBind(Term, Term, Term, Term), // from, to, action, continuation
}
