use super::Term;

#[derive(Debug)]
pub enum PurePrim {
    Nat(u32),
    NatEql(Term, Term),
    NatNeq(Term, Term),
    NatAdd(Term, Term),
    NatSub(Term, Term),
    NatMul(Term, Term),
    NatLt(Term, Term),
    NatDiv(Term, Term),
    NatRem(Term, Term),
    NatGt(Term, Term),
    NatLte(Term, Term),
    NatGte(Term, Term),
    NatAnd(Term, Term),
    NatOr(Term, Term),
    NatXor(Term, Term),
    NatShl(Term, Term),
    NatShr(Term, Term),
    NatToStr(Term),
    Int(i32),
    IntEql(Term, Term),
    IntNeq(Term, Term),
    IntAdd(Term, Term),
    IntSub(Term, Term),
    IntMul(Term, Term),
    IntDiv(Term, Term),
    IntRem(Term, Term),
    IntLt(Term, Term),
    IntGt(Term, Term),
    IntLte(Term, Term),
    IntGte(Term, Term),
    IntAnd(Term, Term),
    IntOr(Term, Term),
    IntXor(Term, Term),
    IntShl(Term, Term),
    IntShr(Term, Term),
    IntToStr(Term),
    Flt(f32),
    FltAdd(Term, Term),
    FltSub(Term, Term),
    FltMul(Term, Term),
    FltDiv(Term, Term),
    FltEql(Term, Term),
    FltNeq(Term, Term),
    FltLt(Term, Term),
    FltGt(Term, Term),
    FltLte(Term, Term),
    FltGte(Term, Term),
    FltMin(Term, Term),
    FltMax(Term, Term),
    FltNeg(Term),
    FltAbs(Term),
    FltSqrt(Term),
    FltFloor(Term),
    FltCeil(Term),
    FltTrunc(Term),
    FltNearest(Term),
    FltToStr(Term),
    NatToInt(Term),
    NatToFlt(Term),
    IntToNat(Term),
    IntToFlt(Term),
    FltToNat(Term),
    FltToLeBin(Term),
    FltToInt(Term),
    Bin(Vec<u8>),
    BinLen(Term),
    BinEql(Term, Term),
    BinGet(Term, Term),
    BinSlice(Term, Term, Term),
    BinAppend(Term, Term),
    BinConcat(Vec<Term>),
    Arr(Vec<Term>),
    ArrLen(Term),
    ArrGet(Term, Term),
    ArrSlice(Term, Term, Term),
    ArrAppend(Term, Term),
    ArrConcat(Vec<Term>),
    Io(u32),
    IoEql(Term, Term),
}

#[derive(Debug)]
pub enum HostPrim {
    IoRead(Term, Term),
    IoWrite(Term, Term),
    IoOpen(Term, Term),
    IoResolve(Term, Term),
    IoSocket(Term),
    IoBind(Term, Term),
    IoConnect(Term, Term),
    IoListen(Term, Term),
    IoAccept(Term),
    IoStartTls(Term, Term),
    IoTlsServerConfig(Term, Term),
    IoStartTlsServer(Term, Term),
    IoSetNonblocking(Term, Term),
    IoSetRecvTimeout(Term, Term),
    IoSetSendTimeout(Term, Term),
    IoSetReuseaddr(Term, Term),
    IoPoll(Term, Term, Term),
    IoClose(Term),
    IoClockWall,
    IoClockMono,
    IoRandom(Term),
    IoArgs,
    IoEnv(Term),
    IoExit(Term),
}

#[derive(Debug)]
pub enum Prim {
    Pure(PurePrim),
    Host(HostPrim),
}
