use super::Subterm;

#[derive(Debug)]
pub enum PurePrim {
    Nat(u32),
    NatEql(Subterm, Subterm),
    NatNeq(Subterm, Subterm),
    NatAdd(Subterm, Subterm),
    NatSub(Subterm, Subterm),
    NatMul(Subterm, Subterm),
    NatLt(Subterm, Subterm),
    NatDiv(Subterm, Subterm),
    NatRem(Subterm, Subterm),
    NatGt(Subterm, Subterm),
    NatLte(Subterm, Subterm),
    NatGte(Subterm, Subterm),
    NatToStr(Subterm),
    Int(i32),
    IntEql(Subterm, Subterm),
    IntNeq(Subterm, Subterm),
    IntAdd(Subterm, Subterm),
    IntSub(Subterm, Subterm),
    IntMul(Subterm, Subterm),
    IntDiv(Subterm, Subterm),
    IntRem(Subterm, Subterm),
    IntLt(Subterm, Subterm),
    IntGt(Subterm, Subterm),
    IntLte(Subterm, Subterm),
    IntGte(Subterm, Subterm),
    IntToStr(Subterm),
    Flt(f32),
    FltAdd(Subterm, Subterm),
    FltSub(Subterm, Subterm),
    FltMul(Subterm, Subterm),
    FltDiv(Subterm, Subterm),
    FltEql(Subterm, Subterm),
    FltNeq(Subterm, Subterm),
    FltLt(Subterm, Subterm),
    FltGt(Subterm, Subterm),
    FltLte(Subterm, Subterm),
    FltGte(Subterm, Subterm),
    FltMin(Subterm, Subterm),
    FltMax(Subterm, Subterm),
    FltNeg(Subterm),
    FltAbs(Subterm),
    FltSqrt(Subterm),
    FltFloor(Subterm),
    FltCeil(Subterm),
    FltTrunc(Subterm),
    FltNearest(Subterm),
    FltToStr(Subterm),
    NatToInt(Subterm),
    NatToFlt(Subterm),
    IntToNat(Subterm),
    IntToFlt(Subterm),
    FltToNat(Subterm),
    FltToInt(Subterm),
    Bin(Vec<u8>),
    BinLen(Subterm),
    BinEql(Subterm, Subterm),
    BinGet(Subterm, Subterm),
    BinSlice(Subterm, Subterm, Subterm),
    BinAppend(Subterm, Subterm),
    BinConcat(Vec<Subterm>),
    Arr(Vec<Subterm>),
    ArrLen(Subterm),
    ArrGet(Subterm, Subterm),
    ArrSlice(Subterm, Subterm, Subterm),
    ArrAppend(Subterm, Subterm),
    ArrConcat(Vec<Subterm>),
    Unit,
}

#[derive(Debug)]
pub enum HostPrim {
    IoPrint(Subterm),
    IoRead,
}

#[derive(Debug)]
pub enum Prim {
    Pure(PurePrim),
    Host(HostPrim),
}

