[package]
name = "curios-prelude"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "The build-scoped archived Curios sys/syn/std prelude"
build = "build.rs"

[lints]
workspace = true

[features]
profile = [
    "dep:tracing",
    "curios-text/profile",
    "curios-core/profile",
    "curios-ersd/profile",
]

[dependencies]
curios-abi = { workspace = true, features = ["archive"] }
curios-base = { workspace = true, features = ["archive"] }
curios-text = { workspace = true, features = ["archive"] }
curios-core = { workspace = true, features = ["archive"] }
curios-ersd = { workspace = true, features = ["archive"] }
rkyv = { workspace = true }
sha2 = "0.11.0"
tracing = { workspace = true, optional = true }

[build-dependencies]
curios-abi = { workspace = true, features = ["archive"] }
curios-base = { workspace = true, features = ["archive"] }
curios-text = { workspace = true, features = ["archive"] }
curios-core = { workspace = true, features = ["archive"] }
curios-ersd = { workspace = true, features = ["archive"] }
rkyv = { workspace = true }
sha2 = "0.11.0"
